### PR TITLE
chore(deps): updating minimatch to ^8.0.0

### PR DESCRIPTION
**Pull request by abellotti**
chore(deps): updating minimatch to ^8.0.0

- Updating minimatch (and all indirect dependencies)  to at least 8.0.0.

### CODE REVIEW

**Review by infinitewarp — APPROVED** [review]
I'm not a node/yarn expert, but LGTM! 👍

**Comment by abellotti** [comment]
Ping @cdcabrera

**Comment by cdcabrera** [comment]
see #207 comment

**Comment by abellotti** [comment]
Closing as per the comment in #207. Wil be handled via a bulk update.

**Pull request closed without merging**
