### PR TITLE
Development Sync

### PR DESCRIPTION
**Pull request by cdcabrera**
## What's included

Development Sync

### Notes
- Moves remaining **refactors for pf4 form fields** with exception
   - Form fields are included on, but not necessarily limited to the following component wrappers
      - the primary view toolbar
      - create credentials dialog
      - create scan dialog
      - add source wizard
   - The remaining PF3 components and styling are used on the login/out template pages and page layou vertical navigation and masthead.

### Coverage and basic unit test check
1. update the NPM packages with `$ yarn`
1. `$ yarn test`
1. confirm tests come back clean

#### Tools needed
- https://github.com/quipucords/quipucords-ui/blob/dev/CONTRIBUTING.md#install

For a quick verification that changes are minimally functioning. There are quirks, and false positive issues, to how this works. Use accordingly.
1. update the NPM packages with `$ yarn`
1. `$ yarn start`
   - you may need to open the browser, http://localhost:3000/client/sources
   - navigate between the views, `sources` `scans` `credentials` using random data

#### Tools needed
- https://github.com/quipucords/quipucords-ui/blob/dev/CONTRIBUTING.md#install

For a slower verification that changes are minimally functioning. Build the GUI and volume into Django setup. The quirks to using this run center around voluming interfering with page and resource loading, expect styling to take a few seconds to load when first navigating.

1. update the NPM packages with `$ yarn`
1. `$ yarn start:stage`
   - you may need to open the browser, https://localhost:5001/login
   - styling on `login` may be partial, **this is expected** (voluming into certain directories causes issues)
   - navigate between the views, `sources` `scans` `credentials` using data you set

### Check the build
1. update the NPM packages with `$ yarn`
1. `$ yarn build`
1. confirm tests come back clean

## Example

...

## Updates issue/story

ongoing

### CODE REVIEW

**Review by bruno-fs — APPROVED** [review]
:+1: LGTM

**Review by nicolearagao — APPROVED** [review]
LGTM 👍🏼

**Review by gtanzillo — APPROVED** [review]
Looks good, thanks @cdcabrera!

**Review by ruda — APPROVED** [review]
LGTM!

```
Test Suites: 103 passed, 103 total
Tests:       361 passed, 361 total
Snapshots:   546 passed, 546 total
Time:        122.647 s, estimated 210 s
Ran all test suites.
✨  Done in 143.41s.Test Suites: 103 passed, 103 total
Tests:       361 passed, 361 total
Snapshots:   546 passed, 546 total
Time:        122.647 s, estimated 210 s
Ran all test suites.
✨  Done in 143.41s.
```

**Pull request merged**
