### PR TITLE
Fix creds in edit source

### PR DESCRIPTION
**Pull request by nicolearagao**
New useEffect: The useEffect that syncs the internal selected state with the selectedOptions prop ensures that when the selectedOptions prop changes (such as when editing a source), the dropdown reflects the correct pre-selected credentials.

### Notes
- fix to [Mirek] When editing a source, “Credentials” field say “0 items selected”. Looks like credentials are not correctly associated with existing source in the list component.
if I edit a source and select new credentials, and then save, these new credentials will be selected when I edit the source again. So this affects only editing after create

### Coverage and basic unit test check
1. update the NPM packages with `$ npm install`
1. `$ npm test`
1. confirm tests come back clean

### Local run check
1. update the NPM packages with `$ npm install`
1. `$ npm run start`
1. confirm connections display as intended

## Example

Screenshot from 2024-10-10 16-51-34
Screenshot from 2024-10-10 16-51-20
Screenshot from 2024-10-10 16-51-14

## Updates issue/story

[DISCOVERY-436](https://issues.redhat.com/browse/DISCOVERY-436)

### CODE REVIEW

**Review by cdcabrera — APPROVED** [review]
Appears to perform as intended in local run. 

Future us note* This component needs to be refactored. It pulls directly from the PF example and may contain other issues that come with being an example

**Comment by mirekdlugosz** [comment]
Maybe I'm doing something wrong, but I don't see any difference. I see the same behavior as when initially reported:

1. Create few credentials of one type
2. Go to Sources, create new source of that type
3. Immediately click kebab for new source and "Edit"
4. In modal "Credentials" says "0 items selected"

I tried using container image from quay (image id `e3c91de8f47b`) and built locally from this branch.

**Comment by nicolearagao** [comment]
> Maybe I'm doing something wrong, but I don't see any difference. I see the same behavior as when initially reported:
> 
> 1. Create few credentials of one type
> 2. Go to Sources, create new source of that type
> 3. Immediately click kebab for new source and "Edit"
> 4. In modal "Credentials" says "0 items selected"
> 
> I tried using container image from quay (image id `e3c91de8f47b`) and built locally from this branch.

huh, that's very weird. Let's take a look at it together.

**Review by mirekdlugosz — APPROVED** [review]
I tried on latest container image (id `77005e3ed963`) and now it works as expected :+1: . I guess the branch was missing some commits from other PRs.

**Pull request merged**
