### PR TITLE
refactor: ds-775 dotenv params for branding display

### PR DESCRIPTION
**Pull request by cdcabrera**
## What's included

- refactor: ds-775 dotenv params for branding display
   * dotenv, remove unneeded prod params
   * build, export UI_BRAND directly from npm script
   * pre, remove dynamic dotenv params for django templates
   * viewLayout, add brand props, expand test
   * helpers, expose brand, display name dotenv params

### Notes
- currently we leave in place the legacy UI branding images. they could be iterated on or we can hold this PR until they're updated
- the legacy brand process was still performing actions related to Django templates, this removes/refactors those facets so everything for branding is controlled by a single `UI_BRAND=true` env value... along with original config values
   - note the update of the shell script
   - note the UI_BRAND=true used in `package.json` branding script

### Coverage and basic unit test check
1. update the NPM packages with `$ npm install`
1. `$ npm test`
1. confirm tests come back as expected

### Local run check
1. update the NPM packages with `$ npm install`
1. `$ npm run start`
   - confirm the ui displays the original "quipucords" logo/title in the upper left corner
   - on confirmation shut down the terminal process
1. after shutting down the process run `$ export UI_BRAND=true; npm start`
   - confirm the ui displays the "Discovery" logo/title in the upper left corner
   - on confirmation shut down the terminal process
   - remember to unset the exported value or you'll potentially receive unexpected results ` $ unset UI_BRAND` when you run another command

## Example

Screenshot 2024-09-20 at 12 22 05 PM
Screenshot 2024-09-20 at 12 20 52 PM

## Updates issue/story

[DISCOVERY-775](https://issues.redhat.com/browse/DISCOVERY-775)

### CODE REVIEW

**Review by mirekdlugosz — APPROVED** [review]

**Comment by bruno-fs** [comment]
After @infinitewarp dug the comments from Justin and his confirmation today, the branding should be "Discovery", not "product discovery" - or am I missing something, @justinkreft?

**Comment by justinkreft** [comment]
Please use "Discovery" without the Red Hat precursor.

**Comment by gtanzillo** [comment]
> After @infinitewarp dug the comments from Justin and his confirmation today, the branding should be "Discovery", not "product discovery" - or am I missing something, @justinkreft?

@bruno-fs, @justinkreft Let's keep the progress moving forward by merging this PR and iterating on the logo discussion. We can take of that in another PR, @cdcabrera is able to change it.

**Review by infinitewarp — APPROVED** [review]

**Comment by cdcabrera** [comment]
@infinitewarp fix for the HTML template pushed

- we had to minimally restore some of the template naming updates
- this time around we opted to use webpack/js instead of a shell script

**Review by infinitewarp — APPROVED** [review]
I pulled the latest commit, and I confirmed that running `npm start` with and without `UI_BRAND=true` in the environment is toggling the SVGs and the title text. Looks good to me!

**Pull request merged**
