### PR TITLE
refactor(Alert): convert alert to PF4 in credential dialog

### PR DESCRIPTION
**Pull request by jenny-s51**
## What's included

...
Converts the instance of `Alert` in createCredentialDialog.js to use new PF4 component/styling.

Towards #91 

## How to test

1. Change line 389 of https://github.com/quipucords/quipucords-ui/compare/dev...jenny-s51:credentialDialogConvertAlert?expand=1#diff-c9e674b4dc402e05f627561a03fa45b3e001693235edd669a9df547cb160522bL387 to `if (!error) {`
2. Go to Credentials -> Add and click on each type 

## Example

...
Before:
Screen Shot 2022-06-30 at 11 27 49 AM
Screen Shot 2022-06-30 at 11 27 57 AM
Screen Shot 2022-06-30 at 11 28 04 AM

After:
Screen Shot 2022-06-30 at 11 29 06 AM
Screen Shot 2022-06-30 at 11 29 12 AM
Screen Shot 2022-06-30 at 11 29 17 AM

## Updates issue/story

https://issues.redhat.com/browse/DISCOVERY-148

### CODE REVIEW

**Comment by cdcabrera** [comment]
@jenny-s51 I went ahead and rebased your PR against the modal styling updates. When you get a minute can you go ahead and take a `before` screenshot.

And here's the after-the-rebase screenshot I have... @bclarhk 
Screen Shot 2022-06-30 at 5 56 57 PM

**Review by cdcabrera — CHANGES_REQUESTED** [review]
Overall code looks good! 

rebase helped out, just need some `before artifacts` and whatever other changes @bclarhk recommends based on the before/after comparison

adding in @ruda to get us used to having QE verify the PF-4 updates

**Review by bclarhk — APPROVED** [review]
Alert icons to be adjusted later as one group. Everything else looks good!

**Comment by cdcabrera** [comment]
@jenny-s51 just a heads up, i'm rebasing, then merging this

**Comment by cdcabrera** [comment]
After the rebase with the modal adjustments we've got 1 additional padding/margin adjustment to add to the Alerts... width @bclarhk @jenny-s51 
Screen Shot 2022-07-06 at 10 46 43 AM

**Pull request merged**
