### PR TITLE
Development Sync

### PR DESCRIPTION
**Pull request by cdcabrera**
## What's included

Development Sync

### Notes
- Moves core PF4 refactors for views
- Does not include
   - pf4 form input updates
   - pf4 page/view toolbar

### Coverage and basic unit test check
1. update the NPM packages with `$ yarn`
1. `$ yarn test`
1. confirm tests come back clean

#### Tools needed
- https://github.com/quipucords/quipucords-ui/blob/dev/CONTRIBUTING.md#install

For a quick verification that changes are minimally functioning. There are quirks, and false positive issues, to how this works. Use accordingly.
1. update the NPM packages with `$ yarn`
1. `$ yarn start`
   - you may need to open the browser, http://localhost:3000/client/sources
   - navigate between the views, `sources` `scans` `credentials` using random data

#### Tools needed
- https://github.com/quipucords/quipucords-ui/blob/dev/CONTRIBUTING.md#install

For a slower verification that changes are minimally functioning. Build the GUI and volume into Django setup. The quirks to using this run center around voluming interfering with page and resource loading, expect styling to take a few seconds to load when first navigating.

1. update the NPM packages with `$ yarn`
1. `$ yarn start:stage`
   - you may need to open the browser, https://localhost:5001/login
   - styling on `login` may be partial, **this is expected** (voluming into certain directories causes issues)
   - navigate between the views, `sources` `scans` `credentials` using data you set

### Check the build
1. update the NPM packages with `$ yarn`
1. `$ yarn build`
1. confirm tests come back clean

### before
Screen Shot 2022-09-16 at 12 52 07 PM
Screen Shot 2022-09-16 at 12 51 37 PM
Screen Shot 2022-09-16 at 12 51 24 PM

### after
Screen Shot 2022-09-16 at 12 46 02 PM

Screen Shot 2022-09-16 at 12 45 45 PM

  
Screen Shot 2022-09-16 at 12 45 28 PM

## Updates issue/story

ongoing

### CODE REVIEW

**Comment by bclarhk** [comment]
Lookin good

**Review by bruno-fs — APPROVED** [review]
I tested locally with latest upstream and downstream discovery. Worked like a charm and is noticeably an improvement over the pf3 version!

I also took a look at the changes and (even though I'm no expert) LGTM :+1:

**Comment by ruda** [comment]
LGTM! Tested with what was purpose and in a real scenarios (network, sat and vcenter) - testlab.

**Review by ruda — COMMENTED** [review]
LGTM.

**Review by ruda — APPROVED** [review]
LGTM.

**Review by gtanzillo — APPROVED** [review]
Looks awesome!! Thanks @cdcabrera

**Pull request merged**
